window.__CODEX_PETS__ = {
  "count": 84,
  "pets": [
    {
      "slug": "battle-damaged-idle",
      "folder": "pets/battle-damaged-idle",
      "id": "battle-damaged-idle",
      "displayName": "Battle-Damaged Idle",
      "description": "A ruined version of the original Idle pet with half a head, one surviving arm, and a nearly legless broken lower body.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/battle-damaged-idle/pet.json",
      "spritesheetFile": "pets/battle-damaged-idle/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "blackbird",
      "folder": "pets/blackbird",
      "id": "blackbird",
      "displayName": "Blackbird",
      "description": "A tiny Machinarium-style mechanical blackbird with brass beak and eye ring, quiet alert posture, and layered iron feather plates.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/blackbird/pet.json",
      "spritesheetFile": "pets/blackbird/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "brass-reed",
      "folder": "pets/brass-reed",
      "id": "brass-reed",
      "displayName": "Brass Reed",
      "description": "A lanky Machinarium saxophone robot with wire-curl hair and a wistful brass tone, reimagined as a compact Codex digital pet.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/brass-reed/pet.json",
      "spritesheetFile": "pets/brass-reed/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "brassbun",
      "folder": "pets/brassbun",
      "id": "brassbun",
      "displayName": "Brassbun",
      "description": "A gentle clockwork rabbit with a worn satchel and a quiet helper spirit.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/brassbun/pet.json",
      "spritesheetFile": "pets/brassbun/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "brassprout",
      "folder": "pets/brassprout",
      "id": "brassprout",
      "displayName": "Brassprout",
      "description": "A sleepy brass pot-bear automaton with three sprouting mechanical leaves.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/brassprout/pet.json",
      "spritesheetFile": "pets/brassprout/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "brew",
      "folder": "pets/brew",
      "id": "brew",
      "displayName": "Brew",
      "description": "A tiny vintage coffee-carrying robot companion with warm worn enamel metal, spring limbs, and gentle steam.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/brew/pet.json",
      "spritesheetFile": "pets/brew/spritesheet.webp",
      "stateNames": [
        "bounce",
        "coffee_break",
        "curious",
        "happy",
        "idle",
        "low_energy",
        "sleep",
        "walk"
      ],
      "stateCount": 8
    },
    {
      "slug": "brigbeak",
      "folder": "pets/brigbeak",
      "id": "brigbeak",
      "displayName": "Brigbeak",
      "description": "A tiny pirate dodo skeleton with a plum-trimmed tricorne, hooked beak, bobbing spine, and jaunty museum-raider swagger.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/brigbeak/pet.json",
      "spritesheetFile": "pets/brigbeak/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "brine-star",
      "folder": "pets/brine-star",
      "id": "brine-star",
      "displayName": "Brine Star",
      "description": "A lean predatory blue sea star with half-lidded eyes, two small fangs, pink nodules, and a sly watchful expression inspired by the reference mural.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/brine-star/pet.json",
      "spritesheetFile": "pets/brine-star/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "brinepaw",
      "folder": "pets/brinepaw",
      "id": "brinepaw",
      "displayName": "Brinepaw",
      "description": "A tiny pirate cat in the Codex pet style, with a huge tricorne hat, bright blue eyes, a fish bandolier, a short harpoon gun, and a sheathed cutlass.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/brinepaw/pet.json",
      "spritesheetFile": "pets/brinepaw/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "bruno",
      "folder": "pets/bruno",
      "id": "bruno",
      "displayName": "Bruno",
      "description": "A sturdy vintage mechanical bulldog companion holding a chunky old revolver, closely based on the supplied Spike-like reference character.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/bruno/pet.json",
      "spritesheetFile": "pets/bruno/spritesheet.webp",
      "stateNames": [
        "curious",
        "grumpy",
        "guard",
        "happy",
        "idle",
        "lookout",
        "sleep",
        "walk"
      ],
      "stateCount": 8
    },
    {
      "slug": "Budley-pet",
      "folder": "pets/Budley-pet",
      "id": "Budley",
      "displayName": "Budley",
      "description": "A round little green robot-creature with soft antennae, curious eyes, and a sweet, slightly dazed personality.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/Budley-pet/pet.json",
      "spritesheetFile": "pets/Budley-pet/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "butch-dog",
      "folder": "pets/butch-dog",
      "id": "butch-dog-machina",
      "displayName": "Butch Dog",
      "description": "A compact Codex pet version of a chubby Machinarium-style robotic bulldog who looks tough but is secretly soft-hearted, always holding a bone.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/butch-dog/pet.json",
      "spritesheetFile": "pets/butch-dog/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "cardinal",
      "folder": "pets/cardinal",
      "id": "cardinal",
      "displayName": "Cardinal",
      "description": "A slim mechanical red-crested cardinal inspired by Machinarium, simplified into a Codex pet sprite.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/cardinal/pet.json",
      "spritesheetFile": "pets/cardinal/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "castle-guard",
      "folder": "pets/castle-guard",
      "id": "castle-guard",
      "displayName": "Castle Guard",
      "description": "A gentle steel castle guard robot with a domed helmet, rounded riveted body, stubby legs, and a tiny toy clutched in its hands.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/castle-guard/pet.json",
      "spritesheetFile": "pets/castle-guard/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "climber-stick",
      "folder": "pets/climber-stick",
      "id": "climber",
      "displayName": "Climber",
      "description": "A quiet climbing stick-figure pet with a red headband, simplified into the Codex digital pet style.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/climber-stick/pet.json",
      "spritesheetFile": "pets/climber-stick/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "copper-cat-package",
      "folder": "pets/copper-cat-package",
      "id": "copper-cat",
      "displayName": "Copper Cat",
      "description": "A friendly Codex pet orange cat reimagined as a whimsical Machinarium-style brass toy.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/copper-cat-package/pet.json",
      "spritesheetFile": "pets/copper-cat-package/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "curlcap-pet",
      "folder": "pets/curlcap-pet",
      "id": "curlcap",
      "displayName": "Curlcap",
      "description": "A sleepy little green wanderer with a curling hat, a fluffy amber ruff, and a quiet mischievous streak.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/curlcap-pet/pet.json",
      "spritesheetFile": "pets/curlcap-pet/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "dandy-beak",
      "folder": "pets/dandy-beak",
      "id": "dandy-beak",
      "displayName": "Dandy Beak",
      "description": "A dapper long-beaked noir bird in a wide hat and striped suit with a tiny shoulder companion.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/dandy-beak/pet.json",
      "spritesheetFile": "pets/dandy-beak/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "dart",
      "folder": "pets/dart",
      "id": "dart",
      "displayName": "Dart",
      "description": "A faithful pink pearl mechanical dragonfly Codex pet with giant glassy eyes, four translucent brass-framed wings, and a delicate segmented tail.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/dart/pet.json",
      "spritesheetFile": "pets/dart/spritesheet.webp",
      "stateNames": [
        "curious",
        "fluff",
        "fly",
        "happy",
        "idle",
        "probe",
        "sleep",
        "walk"
      ],
      "stateCount": 8
    },
    {
      "slug": "dog-creak",
      "folder": "pets/dog-creak",
      "id": "dog-creak",
      "displayName": "Dog Creak",
      "description": "A Codex pet inspired by the dog-like creak creature that freezes into a tiny drawer cabinet under light.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/dog-creak/pet.json",
      "spritesheetFile": "pets/dog-creak/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "droopy7",
      "folder": "pets/droopy7",
      "id": "droopy-7-maintenance-dog",
      "displayName": "Droopy-7",
      "description": "A tiny Codex pet version of Droopy-7, a tired Machinarium-style factory maintenance robot dog with a long face, droopy eyelids, black hanging ears, a worn green hat, and a leaking steam backpack.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/droopy7/pet.json",
      "spritesheetFile": "pets/droopy7/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "fairy-wren",
      "folder": "pets/fairy-wren",
      "id": "fairy-wren",
      "displayName": "Fairy-Wren",
      "description": "A tiny fluffy blue-purple mechanical fairy-wren inspired by Machinarium, simplified into a Codex pet sprite.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/fairy-wren/pet.json",
      "spritesheetFile": "pets/fairy-wren/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "fat-robot",
      "folder": "pets/fat-robot",
      "id": "fat-robot",
      "displayName": "Fat Robot",
      "description": "A chubby rusty bucket robot companion inspired by the stout Machinarium fat robot.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/fat-robot/pet.json",
      "spritesheetFile": "pets/fat-robot/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "flamingo",
      "folder": "pets/flamingo",
      "id": "flamingo",
      "displayName": "flamingo",
      "description": "A graceful machinarium-inspired mechanical flamingo companion.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/flamingo/pet.json",
      "spritesheetFile": "pets/flamingo/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "flying robot",
      "folder": "pets/flying robot",
      "id": "rotor-josef",
      "displayName": "Rotor Josef",
      "description": "A tiny rotor-headed scrapyard scout with a cylindrical metal body, huge eyes, and spindly dangling legs.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/flying robot/pet.json",
      "spritesheetFile": "pets/flying robot/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "freddy-machi",
      "folder": "pets/freddy-machi",
      "id": "freddy-machi",
      "displayName": "Freddy Machi",
      "description": "A Freddy-inspired stage animatronic bear rebuilt as a Codex pet with faithful facial proportions, heavy segmented suit limbs, and a worn Machinarium-like metal finish.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/freddy-machi/pet.json",
      "spritesheetFile": "pets/freddy-machi/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "glint",
      "folder": "pets/glint",
      "id": "glint",
      "displayName": "Glint",
      "description": "A faithful pink mechanical kitten riding a broom, with dreamy soft star particles at the broom tail.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/glint/pet.json",
      "spritesheetFile": "pets/glint/spritesheet.webp",
      "stateNames": [
        "curious",
        "fluff",
        "fly",
        "happy",
        "idle",
        "probe",
        "sleep",
        "walk"
      ],
      "stateCount": 8
    },
    {
      "slug": "glowtail",
      "folder": "pets/glowtail",
      "id": "glowtail",
      "displayName": "Glowtail",
      "description": "A bright neon-green pixel cat with a square head, tiny pale eyes, a gentle blank expression, an arched back, one forepaw stretched forward, sturdy hind legs, and a long tail curling upward.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/glowtail/pet.json",
      "spritesheetFile": "pets/glowtail/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "heron",
      "folder": "pets/heron",
      "id": "heron",
      "displayName": "Heron",
      "description": "A slender mechanical heron Codex pet with an ultra-long straight beak, S-curved neck, layered steel wing plates, brass joints, rusted copper structure, and red-brown throat tassel strands.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/heron/pet.json",
      "spritesheetFile": "pets/heron/spritesheet.webp",
      "stateNames": [
        "curious",
        "fly",
        "happy",
        "idle",
        "melancholy",
        "probe",
        "sleep",
        "walk"
      ],
      "stateCount": 8
    },
    {
      "slug": "honeybee",
      "folder": "pets/honeybee",
      "id": "honeybee",
      "displayName": "Honeybee",
      "description": "A small fluffy mechanical bee inspired by Machinarium, warm, quiet, and clumsy.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/honeybee/pet.json",
      "spritesheetFile": "pets/honeybee/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "inkbit",
      "folder": "pets/inkbit",
      "id": "inkbit",
      "displayName": "Inkbit",
      "description": "A poised blue octopus with a towering spotted mantle, long curling arms, and the cold half-lidded stare of the original painting.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/inkbit/pet.json",
      "spritesheetFile": "pets/inkbit/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "jem",
      "folder": "pets/jem",
      "id": "jem",
      "displayName": "Jem",
      "description": "A faithful mechanical pink Jerry-like mouse Codex pet with oversized round ears, a big cheerful face, blush-pink enamel, cream porcelain muzzle and belly, light antique brass joints, and a long segmented tail.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/jem/pet.json",
      "spritesheetFile": "pets/jem/spritesheet.webp",
      "stateNames": [
        "curious",
        "deep_rest",
        "happy",
        "idle",
        "probe",
        "sit",
        "sleep",
        "walk"
      ],
      "stateCount": 8
    },
    {
      "slug": "josef-bot",
      "folder": "pets/josef-bot",
      "id": "josef-bot",
      "displayName": "Josef Bot",
      "description": "A brass Codex companion inspired by a melancholic scrap robot.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/josef-bot/pet.json",
      "spritesheetFile": "pets/josef-bot/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "koi",
      "folder": "pets/koi",
      "id": "koi",
      "displayName": "Koi",
      "description": "A calm mechanical koi companion pet with ivory and rust-orange layered scales, brass joints, glassy round eyes, translucent fin membranes, and an elegant flowing tail.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/koi/pet.json",
      "spritesheetFile": "pets/koi/spritesheet.webp",
      "stateNames": [
        "curious",
        "float",
        "happy",
        "idle",
        "melancholy",
        "rise",
        "sleep",
        "walk"
      ],
      "stateCount": 8
    },
    {
      "slug": "luna",
      "folder": "pets/luna",
      "id": "luna",
      "displayName": "Luna",
      "description": "A pink-and-cream fairy-tale mechanical moon rocket companion with a tethered moon lamp.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/luna/pet.json",
      "spritesheetFile": "pets/luna/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "machi-cat",
      "folder": "pets/machi-cat",
      "id": "machi-cat",
      "displayName": "Machi Cat",
      "description": "A tiny riveted robot cat with glowing eyes, segmented steel body, wire tail, and thin black legs inspired by a scrapyard automaton.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/machi-cat/pet.json",
      "spritesheetFile": "pets/machi-cat/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "machi-chef",
      "folder": "pets/machi-chef",
      "id": "machi-chef",
      "displayName": "Machi Chef",
      "description": "A tiny anxious robot chef inspired by a rusted storybook kitchen automaton, simplified into a Codex desktop pet.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/machi-chef/pet.json",
      "spritesheetFile": "pets/machi-chef/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "machi-dog",
      "folder": "pets/machi-dog",
      "id": "machi-dog",
      "displayName": "Machi Dog",
      "description": "A tiny rust-bellied mechanical dog inspired by a scrapyard automaton, with clamp jaws and spindly legs.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/machi-dog/pet.json",
      "spritesheetFile": "pets/machi-dog/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "machi-foxy",
      "folder": "pets/machi-foxy",
      "id": "machi-foxy",
      "displayName": "Machi Foxy",
      "description": "A Machinarium-style Codex pet version of Foxy with the same sly stare, pirate eyepatch, hook hand, exposed metal hand, giant ears, toothy grin, narrow torso, and long mechanical legs.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/machi-foxy/pet.json",
      "spritesheetFile": "pets/machi-foxy/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "machi-owl",
      "folder": "pets/machi-owl",
      "id": "machi-owl",
      "displayName": "Machi Owl",
      "description": "A tiny brass mechanical owl rebuilt as a Codex pet, using the side-view Machinarium design as the main truth.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/machi-owl/pet.json",
      "spritesheetFile": "pets/machi-owl/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "marten",
      "folder": "pets/marten",
      "id": "marten",
      "displayName": "Marten",
      "description": "A mischievous yellow-throated marten pet with a Machinarium-inspired brass-mechanical body, black face, golden throat, and huge fluffy tail.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/marten/pet.json",
      "spritesheetFile": "pets/marten/spritesheet.webp",
      "stateNames": [
        "alert",
        "damaged",
        "happy",
        "idle",
        "sleep",
        "walk"
      ],
      "stateCount": 6
    },
    {
      "slug": "mean guard",
      "folder": "pets/mean guard",
      "id": "mean-guard",
      "displayName": "Mean Guard",
      "description": "A tall, stern scrap-metal sentry with a conical helmet, long narrow torso, thin rod limbs, and a chest star emblem.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/mean guard/pet.json",
      "spritesheetFile": "pets/mean guard/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "mechanical-maze-knight",
      "folder": "pets/mechanical-maze-knight",
      "id": "mechanical-maze-knight",
      "displayName": "Mechanical Maze Knight",
      "description": "A battle-worn scrap knight robot pet with a single glowing eye, asymmetrical arms, and a back-mounted ruined blade.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/mechanical-maze-knight/pet.json",
      "spritesheetFile": "pets/mechanical-maze-knight/spritesheet.webp",
      "stateNames": [
        "alert",
        "damaged",
        "happy",
        "idle",
        "sleep",
        "walk"
      ],
      "stateCount": 6
    },
    {
      "slug": "moss-maw",
      "folder": "pets/moss-maw",
      "id": "moss-maw",
      "displayName": "Moss Maw",
      "description": "A strange square-headed scrapyard creature with yellow eyes, a wide toothy mouth, broad sloped shoulders, tiny hands, and newly completed spindly lower legs, reimagined as a Machinarium-style Codex pet.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/moss-maw/pet.json",
      "spritesheetFile": "pets/moss-maw/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "pebb",
      "folder": "pets/pebb",
      "id": "pebb",
      "displayName": "Pebb",
      "description": "A faithful round mechanical penguin Codex pet with a sky-blue worn metal shell, cream belly, warm yellow glowing eyes, yellow beak and feet, pink cheeks, and two tiny pale-blue robot fish hugged tightly in its short arms.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/pebb/pet.json",
      "spritesheetFile": "pets/pebb/spritesheet.webp",
      "stateNames": [
        "cuddle",
        "curious",
        "deep_rest",
        "happy",
        "idle",
        "probe",
        "sleep",
        "walk"
      ],
      "stateCount": 8
    },
    {
      "slug": "pinky",
      "folder": "pets/pinky",
      "id": "pinky",
      "displayName": "Pinky",
      "description": "A faithful mechanical pink panther Codex pet with a long sleepy face, slender toy-metal body, pearl pink enamel, and a laid-back cool expression.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/pinky/pet.json",
      "spritesheetFile": "pets/pinky/spritesheet.webp",
      "stateNames": [
        "curious",
        "fluff",
        "happy",
        "idle",
        "probe",
        "sit",
        "sleep",
        "walk"
      ],
      "stateCount": 8
    },
    {
      "slug": "pip",
      "folder": "pets/pip",
      "id": "pip",
      "displayName": "Pip",
      "description": "A faithful tiny antique brass robot Codex pet based on the provided reference, with a rounded oversized head, warm glowing oval eyes, single ball-tip antenna, tiny ball-jointed limbs, and a gentle lonely storybook mood.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/pip/pet.json",
      "spritesheetFile": "pets/pip/spritesheet.webp",
      "stateNames": [
        "curious",
        "deep_rest",
        "happy",
        "hold_star",
        "idle",
        "probe",
        "sleep",
        "walk"
      ],
      "stateCount": 8
    },
    {
      "slug": "pipe-wrench-robot",
      "folder": "pets/pipe-wrench-robot",
      "id": "pipe-wrench-robot",
      "displayName": "Pipe Wrench Robot",
      "description": "A tiny rusty pipe-wrench robot with a single bolt eye, toothed jaw, stacked metal neck, and spindly wire limbs inspired by Machinarium.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/pipe-wrench-robot/pet.json",
      "spritesheetFile": "pets/pipe-wrench-robot/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "pub-player",
      "folder": "pets/pub-player",
      "id": "pub-player",
      "displayName": "Pub Player",
      "description": "A tiny rusty pub-game robot with a domed tin head, stacked metal body, spindly legs, and a little attached game tray inspired by Machinarium.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/pub-player/pet.json",
      "spritesheetFile": "pets/pub-player/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "redcheek",
      "folder": "pets/redcheek",
      "id": "redcheek-01",
      "displayName": "Redcheek",
      "description": "A small melancholic mechanical sparrow with a chipped red cheek plate, layered brass-and-rust feathers, and delicate hopping legs.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/redcheek/pet.json",
      "spritesheetFile": "pets/redcheek/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "rivet-puff",
      "folder": "pets/rivet-puff",
      "id": "rivet-puff",
      "displayName": "Rivet Puff",
      "description": "A palm-sized round kitten pet reimagined in a Machinarium-inspired mechanical style, with huge dark eyes, tiny ears, a warm brass shell, and a soft shy expression.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/rivet-puff/pet.json",
      "spritesheetFile": "pets/rivet-puff/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "rook",
      "folder": "pets/rook",
      "id": "rook",
      "displayName": "Rook",
      "description": "A faithful Codex pet adaptation of a noir mechanical mouse detective with giant round ears, a worn brown leather hat, a weathered blue-gray trench coat, warm glowing mechanical eyes, no tail, and a small vintage pistol.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/rook/pet.json",
      "spritesheetFile": "pets/rook/spritesheet.webp",
      "stateNames": [
        "brace",
        "curious",
        "grumpy",
        "happy",
        "idle",
        "investigate",
        "sleep",
        "walk"
      ],
      "stateCount": 8
    },
    {
      "slug": "rosefinch",
      "folder": "pets/rosefinch",
      "id": "rosefinch",
      "displayName": "Rosefinch",
      "description": "A warm Machinarium-inspired mechanical rosy finch Codex pet with soft pink winter feathers and hidden brass joints.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/rosefinch/pet.json",
      "spritesheetFile": "pets/rosefinch/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "rustango",
      "folder": "pets/rustango",
      "id": "rustango",
      "displayName": "Rustango",
      "description": "A shy scrapyard lizard-bot who acts cool, built from oxidized brass and patched metal in a Machinarium-inspired Codex pet style.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/rustango/pet.json",
      "spritesheetFile": "pets/rustango/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "rustbeak",
      "folder": "pets/rustbeak",
      "id": "rustbeak",
      "displayName": "RustBeak",
      "description": "A wistful clockwork bird with a brass probe beak, riveted rose-copper shell, and spring legs.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/rustbeak/pet.json",
      "spritesheetFile": "pets/rustbeak/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "rustveil",
      "folder": "pets/rustveil",
      "id": "rustveil",
      "displayName": "Rustveil",
      "description": "A wistful scrap-knight pet with a single bright visor eye and a sword strapped across its back.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/rustveil/pet.json",
      "spritesheetFile": "pets/rustveil/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "samorost-boxbot",
      "folder": "pets/samorost-boxbot",
      "id": "samorost-boxbot",
      "displayName": "Samorost Boxbot",
      "description": "A tiny freestanding riveted box robot with twin bolt eyes, a hanging chin plate, wiry antenna, two clear side arms, and stubby little legs inspired by the attached Samorost-style robot.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/samorost-boxbot/pet.json",
      "spritesheetFile": "pets/samorost-boxbot/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "scarlet-ibis",
      "folder": "pets/scarlet-ibis",
      "id": "scarlet-ibis",
      "displayName": "Scarlet Ibis",
      "description": "A serene mechanical scarlet ibis inspired by Machinarium, built as a Codex pet.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/scarlet-ibis/pet.json",
      "spritesheetFile": "pets/scarlet-ibis/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "scrib-codex-pet",
      "folder": "pets/scrib-codex-pet",
      "id": "scrib",
      "displayName": "Scrib",
      "description": "A tiny hand-drawn black sketch figure inspired by a Machinarium notebook doodle, simplified into a Codex desktop pet.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/scrib-codex-pet/pet.json",
      "spritesheetFile": "pets/scrib-codex-pet/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "skipp",
      "folder": "pets/skipp",
      "id": "skipp",
      "displayName": "Skipp",
      "description": "A faithful Codex pet adaptation of a retro mechanical sea captain with a huge long nose, curled mustache, worn blue captain coat and tricorn hat, brass joints, and stout little metal boots.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/skipp/pet.json",
      "spritesheetFile": "pets/skipp/spritesheet.webp",
      "stateNames": [
        "brace",
        "curious",
        "grumpy",
        "happy",
        "idle",
        "lookout",
        "sleep",
        "walk"
      ],
      "stateCount": 8
    },
    {
      "slug": "smoking-robot",
      "folder": "pets/smoking-robot",
      "id": "smoking-robot",
      "displayName": "Smoking Robot",
      "description": "A broken rusty smoking robot companion inspired by the slumped Machinarium wall robot.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/smoking-robot/pet.json",
      "spritesheetFile": "pets/smoking-robot/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "snoo",
      "folder": "pets/snoo",
      "id": "snoo",
      "displayName": "Snoo",
      "description": "A faithful pink-white mechanical Snoopy-style companion dog Codex pet with oversized round head, soft drooping ears, rose goggles, plush enamel body, and gentle rose-gold joints.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/snoo/pet.json",
      "spritesheetFile": "pets/snoo/spritesheet.webp",
      "stateNames": [
        "curious",
        "deep_rest",
        "happy",
        "idle",
        "sip",
        "sit",
        "sleep",
        "walk"
      ],
      "stateCount": 8
    },
    {
      "slug": "spike",
      "folder": "pets/spike",
      "id": "spike",
      "displayName": "Spike",
      "description": "A quiet mechanical cactus companion in a pink flower pot, with warm lamp eyes and a tiny blossom.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/spike/pet.json",
      "spritesheetFile": "pets/spike/spritesheet.webp",
      "stateNames": [
        "active",
        "curious",
        "happy",
        "hop",
        "idle",
        "melancholy",
        "sleep",
        "walk"
      ],
      "stateCount": 8
    },
    {
      "slug": "split-chip",
      "folder": "pets/split-chip",
      "id": "split-chip",
      "displayName": "Split Chip",
      "description": "A half-destroyed doll robot with an exposed red brain chip, dragging itself onward with pitiful, dangerous determination.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/split-chip/pet.json",
      "spritesheetFile": "pets/split-chip/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "spot",
      "folder": "pets/spot",
      "id": "spot",
      "displayName": "Spot",
      "description": "A tiny pink wheeled scout companion robot with twin warm searchlight eyes and a pink baseball cap.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/spot/pet.json",
      "spritesheetFile": "pets/spot/spritesheet.webp",
      "stateNames": [
        "active",
        "curious",
        "happy",
        "hop",
        "idle",
        "melancholy",
        "sleep",
        "walk"
      ],
      "stateCount": 8
    },
    {
      "slug": "springtrap-machi",
      "folder": "pets/springtrap-machi",
      "id": "springtrap-machi",
      "displayName": "Springtrap Machi",
      "description": "A decayed rabbit animatronic rebuilt as a Codex pet with Springtrap-like broken ears, torn suit patches, exposed wires, and a worn Machinarium-style metal finish.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/springtrap-machi/pet.json",
      "spritesheetFile": "pets/springtrap-machi/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "stilt",
      "folder": "pets/stilt",
      "id": "stilt",
      "displayName": "Stilt",
      "description": "A calm elegant black-necked stilt Codex pet inspired by Machinarium, with black and white enamel feathers, a needle-thin black mechanical beak, and extremely long slender pink legs.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/stilt/pet.json",
      "spritesheetFile": "pets/stilt/spritesheet.webp",
      "stateNames": [
        "curious",
        "fluff",
        "fly",
        "happy",
        "idle",
        "probe",
        "sleep",
        "walk"
      ],
      "stateCount": 8
    },
    {
      "slug": "sunny",
      "folder": "pets/sunny",
      "id": "sunny",
      "displayName": "Sunny",
      "description": "A lounging beach-sunbathing mechanical mouse scene pet with white sunglasses, a pink-and-cream parasol, a quilted pink mat, and no visible tail.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/sunny/pet.json",
      "spritesheetFile": "pets/sunny/spritesheet.webp",
      "stateNames": [
        "curious",
        "float",
        "happy",
        "idle",
        "melancholy",
        "probe",
        "sleep",
        "walk"
      ],
      "stateCount": 8
    },
    {
      "slug": "tavern-lampbot",
      "folder": "pets/tavern-lampbot",
      "id": "tavern-lampbot",
      "displayName": "Tavern Lampbot",
      "description": "A tiny bartender-like scrapyard robot with a wide lamp-eyed head, a narrow riveted torso, thin hose arms, and newly completed little legs and shoes.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/tavern-lampbot/pet.json",
      "spritesheetFile": "pets/tavern-lampbot/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "the-drummer",
      "folder": "pets/the-drummer",
      "id": "the-drummer",
      "displayName": "The Drummer",
      "description": "A frog-like Machinarium robot drummer turned into a compact Codex digital pet.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/the-drummer/pet.json",
      "spritesheetFile": "pets/the-drummer/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "tin-grin",
      "folder": "pets/tin-grin",
      "id": "tin-grin",
      "displayName": "Tin Grin",
      "description": "A wiry hand-drawn robot with an AI badge and a crooked grin, remade as a tiny Codex pet.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/tin-grin/pet.json",
      "spritesheetFile": "pets/tin-grin/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "tin-terrier",
      "folder": "pets/tin-terrier",
      "id": "tin-terrier",
      "displayName": "Tin Terrier",
      "description": "A tiny Machinarium clamp-snouted dog with a faded pink barrel body and four thin wire legs, rebuilt as a compact Codex pet.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/tin-terrier/pet.json",
      "spritesheetFile": "pets/tin-terrier/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "tinward-pet",
      "folder": "pets/tinward-pet",
      "id": "tinward",
      "displayName": "Tinward",
      "description": "A tiny tin knight with a bright orange scarf, a soft black visor, and a brave but slightly dreamy heart.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/tinward-pet/pet.json",
      "spritesheetFile": "pets/tinward-pet/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "tomo",
      "folder": "pets/tomo",
      "id": "tomo",
      "displayName": "Tomo",
      "description": "A faithful pink Tom-like mechanical cat Codex pet based on the provided reference image, with a wide soft hat, warm friendly face, plush-toy body, and light antique rose-gold joints.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/tomo/pet.json",
      "spritesheetFile": "pets/tomo/spritesheet.webp",
      "stateNames": [
        "curious",
        "deep_rest",
        "happy",
        "idle",
        "probe",
        "sit",
        "sleep",
        "walk"
      ],
      "stateCount": 8
    },
    {
      "slug": "tsuru",
      "folder": "pets/tsuru",
      "id": "red-crown-crane",
      "displayName": "tsuru",
      "description": "A quiet, dignified mechanical red-crowned crane inspired by Machinarium, with ivory paper-like feathers, a black neck, black tail and wing tips, and a clear red crown.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/tsuru/pet.json",
      "spritesheetFile": "pets/tsuru/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "turaco",
      "folder": "pets/turaco",
      "id": "turaco",
      "displayName": "Turaco",
      "description": "A slim olive-green mechanical turaco inspired by Machinarium, matching the provided Turaco-01 reference with a tall soft red crest, red inner wing feathers, red eye ring, white cheek patch, small red beak, and long dark tail.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/turaco/pet.json",
      "spritesheetFile": "pets/turaco/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "velmour",
      "folder": "pets/velmour",
      "id": "velmour",
      "displayName": "velmour",
      "description": "A lively machinarium-inspired mechanical black hummingbird companion.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/velmour/pet.json",
      "spritesheetFile": "pets/velmour/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "vendo",
      "folder": "pets/vendo",
      "id": "vendo",
      "displayName": "Vendo",
      "description": "A dented vending-machine robot with a coin-slot mouth, faded warning decals, and a shy Machinarium-style wobble.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/vendo/pet.json",
      "spritesheetFile": "pets/vendo/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "vermora",
      "folder": "pets/vermora",
      "id": "vermora",
      "displayName": "Vermora",
      "description": "A calm elegant mechanical painted stork Codex pet inspired by Machinarium, with a very long yellow-orange beak, white body feathers, black patterned wing feathers, soft pink tail gradient, orange bare head skin, and slender pale pink legs.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/vermora/pet.json",
      "spritesheetFile": "pets/vermora/spritesheet.webp",
      "stateNames": [
        "blink",
        "busy",
        "curious",
        "damaged",
        "fly",
        "happy",
        "idle",
        "sleep",
        "walk"
      ],
      "stateCount": 9
    },
    {
      "slug": "walle",
      "folder": "pets/walle",
      "id": "scrapling",
      "displayName": "Scrapling",
      "description": "An original Codex pet inspired by a small cleanup robot, mixing Machinarium melancholy with sturdy treaded utility charm.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/walle/pet.json",
      "spritesheetFile": "pets/walle/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "wheelbox",
      "folder": "pets/wheelbox",
      "id": "wheelbox",
      "displayName": "Wheelbox",
      "description": "A tiny Machinarium-style wheeled helper robot with a box body and a gentle single eye.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/wheelbox/pet.json",
      "spritesheetFile": "pets/wheelbox/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "whisk",
      "folder": "pets/whisk",
      "id": "whisk",
      "displayName": "Whisk",
      "description": "A faithful pink mechanical cat-car Codex pet with a huge round head, sausage-shaped body, tiny wheel feet, metallic whiskers, and a clever slightly fierce face.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/whisk/pet.json",
      "spritesheetFile": "pets/whisk/spritesheet.webp",
      "stateNames": [
        "curious",
        "deep_rest",
        "happy",
        "idle",
        "roll_glide",
        "sleep",
        "tiny_hop",
        "walk"
      ],
      "stateCount": 8
    },
    {
      "slug": "white-eye",
      "folder": "pets/white-eye",
      "id": "white-eye",
      "displayName": "White-Eye",
      "description": "A small machinarium-inspired mechanical white-eye songbird companion.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/white-eye/pet.json",
      "spritesheetFile": "pets/white-eye/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    },
    {
      "slug": "wreckling",
      "folder": "pets/wreckling",
      "id": "wreckling",
      "displayName": "Wreckling",
      "description": "A battle-damaged little scrapyard robot with a cracked chest cavity, one frayed wire hand, one limping leg, and a stubborn Machinarium-like presence.",
      "spritesheetPath": "spritesheet.webp",
      "petJsonPath": "pets/wreckling/pet.json",
      "spritesheetFile": "pets/wreckling/spritesheet.webp",
      "stateNames": [],
      "stateCount": 0
    }
  ]
};
